### ISSUE TITLE
Error reported by browser.

### ISSUE THREAD

**Issue by fwesleyms** [danilomacb/insta-search-bar#1]
Browser reports this error:

"action": {
    "default_popup": "popup.html"
  },

followed by this message 
'action' requires canary channel or newer, but this is the stable channel.

**Comment by danilomacb** [comment]
It's hard for me to understand what is going wrong with this information. I tested in Windows and Linux, with google chrome and chromium, everything is working fine here. Are you using google chrome canary? I didn't test it, or maybe something going wrong with the installation. Anyway, I started the process to publish the extension in the chrome store, if you want, you can wait to download it there.

**Comment by danilomacb** [comment]
I released the extension on Chrome Store, please try to download it there. I will close this issue, if you download by Chrome Store and another error occurred, you can open a new one.

https://chrome.google.com/webstore/detail/insta-search-bar/jmcnkbjgbbdncalgbnemahbhpkhnkckl
